#ifndef __RHI_COMMON_H__
#define __RHI_COMMON_H__

// Default Server configuration
#define RHI_SERVER_DEFAULT_OUT_PACKET_BUFFER_MAX_SIZE 500000
#define RHI_SERVER_DEFAULT_RTP_PORT 20000
#define RHI_SERVER_DEFAULT_RTCP_PORT RHI_SERVER_DEFAULT_RTP_PORT + 1
#define RHI_SERVER_DEFAULT_TTL 225
#define RHI_SERVER_DEFAULT_ESTIMATED_SESSION_BANDWIDTH 6000
#define RHI_SERVER_DEFAULT_MAXCNAME_LEN 100
#define RHI_SERVER_DEFAULT_PORT 8554


#endif